name: Build Theme Release

on:
   push:
      tags:
         - "v*"
   workflow_dispatch:

jobs:
   package:
      runs-on: ubuntu-latest
      env:
         NODE_ENV: production
         TERM: xterm-256color
         FORCE_COLOR: 1
      steps:
         - name: Check out repository
           uses: actions/checkout@v4

         - name: Get package.json version
           id: get_version
           run: |
              VERSION=$(node -p "require('./package.json').version")
              echo "Package version: $VERSION"
              echo "version=$VERSION" >> $GITHUB_OUTPUT

              IS_DRAFT="false"
               if [[ "$VERSION" == *"-"* ]]; then
                  IS_DRAFT="true"
               fi
              echo "is_draft=$IS_DRAFT" >> $GITHUB_OUTPUT

              IS_PRERELEASE="false"
               if [[ "$VERSION" == *"alpha"* || "$VERSION" == *"beta"* || "$VERSION" == *"rc"* ]]; then
                  IS_PRERELEASE="true"
               fi
              echo "is_prerelease=$IS_PRERELEASE" >> $GITHUB_OUTPUT

         - name: Set up Node.js
           uses: actions/setup-node@v4
           with:
              node-version: 22
              cache: npm

         - name: Install dependencies
           run: npm ci

         - name: Build distributable zip
           run: |
              npm run build
         - name: Print build outputs
           if: always()
           run: |
              echo "Contents of dist/:"
              ls -la dist

              echo "Contents of dist/civique/:"
              ls -la dist/civique

              echo "Contents of dist/civique-${{ steps.get_version.outputs.version }}.zip:"
              unzip -l dist/civique-${{ steps.get_version.outputs.version }}.zip

         - name: Upload artifact
           uses: actions/upload-artifact@v4
           with:
              name: civique
              path: dist/civique-${{ steps.get_version.outputs.version }}.zip

         - name: Create Release
           id: create_release
           uses: actions/create-release@v1
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           with:
              tag_name: ${{ github.ref }}
              release_name: Civique ${{ steps.get_version.outputs.version }}
              draft: ${{ steps.get_version.outputs.is_draft }}
              prerelease: ${{ steps.get_version.outputs.is_prerelease }}

         - name: Upload Release Asset
           uses: actions/upload-release-asset@v1
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: ./dist/civique-${{ steps.get_version.outputs.version }}.zip
              asset_name: civique-${{ steps.get_version.outputs.version }}.zip
              asset_content_type: application/zip
