name: Build Theme Release

on:
   push:
      tags:
         - "v*"
   workflow_dispatch:

permissions: write-all
jobs:
   package:
      runs-on: ubuntu-latest
      steps:
         - name: Check out repository
           uses: actions/checkout@v4

         - name: Get package.json version
           id: get_version
           run: |
              VERSION=$(node -p "require('./package.json').version")
              echo "Package version: $VERSION"
              echo "version=$VERSION" >> $GITHUB_OUTPUT

         - name: Set up Node.js
           uses: actions/setup-node@v4
           with:
              node-version: 22
              cache: npm

         - name: Install dependencies
           run: npm ci

         - name: Build distributable zip
           run: |
              npm run build
         - name: Print build outputs
           if: always()
           run: |
              echo "Contents of dist/:"
              ls -la dist

              echo "Contents of dist/civique/:"
              ls -la dist/civique

              echo "Contents of dist/civique-${{ steps.get_version.outputs.version }}.zip:"
              unzip -l dist/civique-${{ steps.get_version.outputs.version }}.zip

         - name: Upload artifact
           uses: actions/upload-artifact@v4
           with:
              name: civique
              path: dist/civique-${{ steps.get_version.outputs.version }}.zip

         - name: Create Release
           id: create_release
           uses: actions/create-release@v1
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           with:
              tag_name: ${{ github.ref_name }}
              release_name: Civique ${{ steps.get_version.outputs.version }}
              draft: false
              prerelease: false

         - name: Upload Release Asset
           uses: actions/upload-release-asset@v1
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: ./dist/civique-${{ steps.get_version.outputs.version }}.zip
              asset_name: civique-${{ steps.get_version.outputs.version }}.zip
              asset_content_type: application/zip
